# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='default title', max_length=300),
            preserve_default=False,
        ),
    ]
