# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('shipping_instructions', models.TextField(null=True)),
                ('is_enabled_exchange', models.BooleanField(default=False)),
                ('preferences', models.TextField(null=True)),
                ('fb_profile_url', models.URLField(null=True)),
                ('twitter_profile_url', models.URLField(null=True)),
                ('website_url', models.URLField(null=True)),
                ('wishlist_url', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
